package orca.ahab.libndl;

import org.apache.log4j.Level;
import org.apache.log4j.Logger;

public class LIBNDL {

	private static Logger logger;
	
	public static Logger logger(){
		return logger;
	}
	
	public static void setLogger(){
		logger = Logger.getLogger(LIBNDL.class.getCanonicalName());
		logger.setLevel(Level.DEBUG);
	}
	

	
	/*
	 *  get a live slice from a controller using a context generated by libtransport
	 *  
	public static Slice getSlice(Context c, String sliceName){
		return null;
	}
	*/
}
